export const STATS_CONFIG = [
  {
    id: 'total',
    title: 'Total Products',
    icon: 'FaBox',
    color: 'blue',
    gradientFrom: 'from-blue-50',
    gradientTo: 'to-azurio/10',
    borderColor: 'border-blue-100',
    iconBg: 'from-azurio to-blue-500',
    badgeColor: 'text-blue-600 bg-blue-100',
  },
  {
    id: 'value',
    title: 'Total Inventory Value',
    icon: 'FaDollarSign',
    color: 'purple',
    gradientFrom: 'from-purple-50',
    gradientTo: 'to-purple-100/50',
    borderColor: 'border-purple-100',
    iconBg: 'from-purple-500 to-purple-600',
    badgeColor: 'text-purple-600 bg-purple-100',
  },
  {
    id: 'average',
    title: 'Average Price',
    icon: 'FaChartLine',
    color: 'emerald',
    gradientFrom: 'from-emerald-50',
    gradientTo: 'to-emerald-100/50',
    borderColor: 'border-emerald-100',
    iconBg: 'from-emerald-500 to-emerald-600',
    badgeColor: 'text-emerald-600 bg-emerald-100',
  },
];
